name: local_people_core
description: A new Flutter package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # Service locator
  get_it: ^2.0.1
  flutter_spinkit: ^4.1.2+1
  intl: ^0.16.1
  provider: ^4.1.3
  # Data
  equatable: ^0.6.0
  meta: ^1.1.6
  flutter_bloc: ^6.1.3
  formz: ^0.3.0
  # rxdart: ^0.23.0
  # UI
  # flutter_svg: ^0.18.1
  http: ^0.12.1
  # Auth0
  flutter_appauth: ^0.9.1
  flutter_secure_storage: ^3.3.3
  # Data Source
  objectdb: ^1.2.1
  path_provider: ^1.4.0
  # Remote API
  data_connection_checker: ^0.3.4
  logging: 0.11.4
  dio: any
  # Json annotator
  json_annotation: any
  # API Manager
  retrofit: any
  #splash screen
  #splashscreen: 1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation: ^0.17.10+1
  retrofit_generator: any
  build_runner: any
  json_serializable: any
  built_value_generator: any
  # Unit test
  test:
  bloc_test: any
  mockito: ^4.1.0

dependency_overrides:
  analyzer: ^0.41.1
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  assets:
    - packages/local_people_core/assets/images/app-logo.png
    - packages/local_people_core/assets/images/company-logo.png
  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
fonts:
  - family: Merriweather
    fonts:
      - asset: packages/local_people_core/assets/fonts/Merriweather-Black.ttf
        weight: 900
  - family: RedHatDisplay
    fonts:
      - asset: packages/local_people_core/assets/fonts/RedHatDisplay-Regular.ttf
        weight: 400
      - asset: packages/local_people_core/assets/fonts/RedHatDisplay-Medium.ttf
        weight: 500
      - asset: packages/local_people_core/assets/fonts/RedHatDisplay-Bold.ttf
        weight: 700

#fonts:
#  - family: Inter
#    fonts:
#      - assets: packages/local_people_core/assets/fonts/Inter/OFL.txt
#      - assets: packages/local_people_core/assets/fonts/Inter/Inter-Thin.ttf
#        weight: 100
#      - assets: packages/local_people_core/assets/fonts/Inter/Inter-ExtraLight.ttf
#        weight: 200
#      - assets: packages/local_people_core/assets/fonts/Inter/Inter-Light.ttf
#        weight: 300
#      - assets: packages/local_people_core/assets/fonts/Inter/Inter-Regular.ttf
#        weight: 400
#      - assets: packages/local_people_core/assets/fonts/Inter/Inter-Medium.ttf
#        weight: 500
#      - assets: packages/local_people_core/assets/fonts/Inter/Inter-SemiBold.ttf
#        weight: 600
#      - assets: packages/local_people_core/assets/fonts/Inter/Inter-Bold.ttf
#        weight: 700
#      - assets: packages/local_people_core/assets/fonts/Inter/Inter-ExtraBold.ttf
#        weight: 800
#      - assets: packages/local_people_core/assets/fonts/Inter/Inter-Black.ttf
#        weight: 900
