name: local_people_core
description: A new Flutter package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # Service locator
  get_it: ^7.1.3
  flutter_spinkit: ^5.0.0
  intl: ^0.17.0
  provider: ^5.0.0
  # Data
  equatable: ^2.0.2
  meta: ^1.1.6
  flutter_bloc: ^7.0.1
  formz: ^0.4.0
  rxdart: ^0.23.0
  # UI
  http: ^0.12.2 # ^0.13.3
  # Auth0
  flutter_appauth: ^0.9.2+6 # ^1.0.0
  flutter_secure_storage: ^4.2.0
  # Data Source
  objectdb: ^1.2.1
  path_provider: ^2.0.2
  # Remote API
  data_connection_checker: ^0.3.4
  logging: ^1.0.1
  dio: ^3.0.9
  # Json annotator
  json_annotation: ^3.1.0 # ^4.0.1
  # API Manager
  built_value: ^7.1.0
  # protobuf: <=0.13.15
  retrofit: ^1.0.0
  #splash screen
  #splashscreen: 1.2.0
  flutter_icons: ^1.1.0
  # uuid: ^3.0.4
  cached_network_image: ^2.3.3
  google_place: ^0.3.3 # ^0.4.0
  image_picker: ^0.6.7+22 # ^0.6.2 # ^0.7.0
  # multi_image_picker: ^4.8.0
  material_segmented_control: ^3.1.2
  material_floating_search_bar: ^0.3.4
  # flutter_webview_plugin: ^0.3.11
  # webview_flutter: ^2.0.4
  # oauth2: ^1.5.0
  # numberpicker: ^2.1.1
  # flutter_typeahead: ^2.0.0
  flutter_form_builder: ^6.0.0-nullsafety.0 #^6.0.0 # ^3.14.0
  # form_builder_image_picker: ^1.0.0-nullsafety.0
  google_maps_flutter: ^0.5.26+4 # ^2.0.0 # ^0.5.26+4
  flutter_screenutil: ^5.0.0
  flutter_tags: ^0.4.9+1
  mime: ^1.0.0
  progressive_image: ^2.0.0
  flutter_svg: any #^0.22.0
  flutter_svg_provider: ^0.1.8
  flutter_inappwebview: ^5.3.2
  permission_handler: 5.1.0+2 # ^6.0.1 # ^5.1.0+2 # ^6.0.0
  sliver_fab: ^1.0.0
  flutter_linear_datepicker: ^2.0.0
  smooth_star_rating: ^1.1.1
  # shared_preferences: ^0.5.12+4
  overlay_dialog: ^0.2.0
  after_layout: ^1.1.0
  scoped_model: ^1.1.0
  provide: ^1.0.2
  rflutter_alert: ^2.0.2
  flutter_typeahead: ^2.0.0
  snapping_sheet: ^3.1.0
  page_indicator: ^0.4.1
  sqflite: ^1.1.6
  dio_http_cache: ^0.2.11
  localstorage: ^4.0.0+1
  sizer: ^2.0.10
  # scrollable_positioned_list: ^0.1.10
  # shamsi_date: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # intl_translation: ^0.17.10+1
  retrofit_generator: ^1.4.1+3
  build_test: any
  build_runner: ^1.10.0
  json_serializable: ^3.5.0 # ^4.0.2
  built_value_generator: ^7.1.0
  # Unit test
  test:
  bloc_test: ^8.0.1
  mockito: ^5.0.7
  mocktail: ^0.1.1
  flutter_driver:

dependency_overrides:
  analyzer: ^0.41.1
  dart_style: '>=1.3.13 <=1.3.13'
  test_api: ^0.2.19
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  assets:
    - packages/local_people_core/assets/images/app-logo.png
    - packages/local_people_core/assets/images/company-logo.png
    - packages/local_people_core/assets/images/local-people-logo.png
    - packages/local_people_core/assets/images/verified-icon.png
    - packages/local_people_core/assets/images/delete-job-icon.png
    - packages/local_people_core/assets/images/package-icon.png
    - packages/local_people_core/assets/images/rectangle.svg
    - packages/local_people_core/assets/images/add-photo-icon.svg
    - packages/local_people_core/assets/images/background.svg
    - packages/local_people_core/assets/images/camera.svg
    - packages/local_people_core/assets/images/app-logo.svg
    - packages/local_people_core/assets/images/heart.svg
    - packages/local_people_core/assets/images/dis-approved.svg
    - packages/local_people_core/assets/images/minus.svg
    - packages/local_people_core/assets/images/plus.svg
    - packages/local_people_core/assets/images/send.svg
    - packages/local_people_core/assets/images/verified.svg
    - packages/local_people_core/assets/images/star.svg
    - packages/local_people_core/assets/images/schedule-icon.svg
    - packages/local_people_core/assets/images/schedule-active-icon.svg
    - packages/local_people_core/assets/images/your-job-icon.svg
    - packages/local_people_core/assets/images/your-job-active-icon.svg
    - packages/local_people_core/assets/images/search-icon.svg
    - packages/local_people_core/assets/images/search-active-icon.svg
    - packages/local_people_core/assets/images/messages-icon.svg
    - packages/local_people_core/assets/images/messages-active-icon.svg
    - packages/local_people_core/assets/images/more-icon.svg
    - packages/local_people_core/assets/images/more-active-icon.svg
    - packages/local_people_core/assets/images/opportunities-icon.svg
    - packages/local_people_core/assets/images/opportunities-active-icon.svg
    - packages/local_people_core/assets/images/trader-profile-photo.png
    - packages/local_people_core/assets/images/client-profile-photo.png
    - packages/local_people_core/assets/images/error-icon.svg
    - packages/local_people_core/assets/images/package-grey.svg
    - packages/local_people_core/assets/images/package-orange.svg
    - packages/local_people_core/assets/images/success.png
    - packages/local_people_core/assets/images/package-green.svg
  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
fonts:
  - family: Merriweather
    fonts:
      - asset: packages/local_people_core/assets/fonts/Merriweather-Black.ttf
        weight: 900
      - asset: packages/local_people_core/assets/fonts/Merriweather-Bpld.ttf
        weight: 700
  - family: RedHatDisplay
    fonts:
      - asset: packages/local_people_core/assets/fonts/RedHatDisplay-Regular.ttf
        weight: 400
      - asset: packages/local_people_core/assets/fonts/RedHatDisplay-Medium.ttf
        weight: 500
      - asset: packages/local_people_core/assets/fonts/RedHatDisplay-Bold.ttf
        weight: 700
  - family: Inter
    fonts:
      - assets: packages/local_people_core/assets/fonts/Inter/Inter-Regular.ttf
        weight: 400
      - assets: packages/local_people_core/assets/fonts/Inter/Inter-Medium.ttf
        weight: 500
      - assets: packages/local_people_core/assets/fonts/Inter/Inter-Bold.ttf
        weight: 700
